source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ios-rrule_parser_Example', :exclusive => true do
  pod 'ios-rrule_parser', :path => '../'
end

target 'ios-rrule_parser_Tests', :exclusive => true do
  pod 'ios-rrule_parser', :path => '../'

  
end
